---

- hosts: server
  become: yes
  become_method: sudo

  roles:
    - zabbix-server
    - mysql

- hosts: agent
  become: yes
  become_method: sudo

  roles:
    - zabbix-agent

#- hosts: proxy
#  become: yes
#  become_method: sudo
#
#  roles:
#    - zabbix-server
#    - zabbix-client
