---
- name: download packages
  get_url: url={{ item }} dest=/tmp/
  with_items:
    - http://repo.zabbix.com/zabbix/3.0/debian/pool/main/z/zabbix/zabbix-agent_3.0.3-1+jessie_amd64.deb

- name: install deb packages 
  apt: deb={{ item }} update_cache=yes state=present
  with_items:
    - /tmp/zabbix-agent_3.0.3-1+jessie_amd64.deb

