---
- name: check if DBHost in file is there
  command: grep "# DBHost=" /etc/zabbix/zabbix_server.conf
  register: checkmyconf
  always_run: True
  ignore_errors: True
  changed_when: False
  
- name: Insert DBHost for zabbix_server.conf file
  lineinfile: 
    dest: /etc/zabbix/zabbix_server.conf
    backup: yes
    regexp: ^# DBHost=
    line: DBHost={{ DBHost }}
  when: checkmyconf.rc == 0

- name: Insert DBHost for zabbix_server.conf file if "# DBHost=" is gone
  lineinfile: 
    dest: /etc/zabbix/zabbix_server.conf
    backup: yes
    regexp: ^DBHost=
    line: DBHost={{ DBHost }}
  when: checkmyconf.rc == 1

- name: Insert DBName for zabbix_server.conf file
  lineinfile: 
    dest: /etc/zabbix/zabbix_server.conf
    regexp: ^DBName=
    line: DBName={{ DBName }}

- name: Insert DBUser for zabbix_server.conf file
  lineinfile: 
    dest: /etc/zabbix/zabbix_server.conf
    regexp: ^DBUser=
    line: DBUser={{ DBUser }}

- name: check if DBPassword in file is there
  command: grep "# DBPassword=" /etc/zabbix/zabbix_server.conf
  register: checkmyconf3
  always_run: True
  ignore_errors: True
  changed_when: False

- name: Insert DBPassword for zabbix_server.conf file
  lineinfile: 
    dest: /etc/zabbix/zabbix_server.conf
    regexp: ^# DBPassword=
    line: DBPassword={{ DBPassword }}
  when: checkmyconf3.rc == 0

- name: Insert DBPassword for zabbix_server.conf file if "# DBPassword=" is gone
  lineinfile: 
    dest: /etc/zabbix/zabbix_server.conf
    regexp: ^DBPassword=
    line: DBPassword={{ DBPassword }}
  when: checkmyconf3.rc == 1
  notify: restart apache2
