---
- name: download packages
  get_url: url={{ item }} dest=/tmp/
  with_items:
    - http://repo.zabbix.com/zabbix/3.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.0-1+trusty_all.deb
    - http://repo.zabbix.com/zabbix/3.0/ubuntu/pool/main/z/zabbix/zabbix-frontend-php_3.0.1-1+trusty_all.deb
    

- name: provide information about new .deb packages
  dpkg_selections: name={{ item }} selection=install
  with_items:
    - zabbix-release_3.0-1+trusty_all.deb
    - zabbix-frontend-php_3.0.1-1+trusty_all.deb
    


                   
  


